# FIXME: do it right.
# TODO: implement CMake

all: units.cc
	g++ -std=c++11 -g -Wall -o ../bin/units units.cc ../src/fevor_crystal.hh ../src/fevor_crystal.cc ../src/vector_tensor_opperations.hh ../src/vector_tensor_opperations.cc
